### ISSUE TITLE
react-native 0.16 support

### ISSUE THREAD

**Issue by guillaumemorin** [bamlab/rn-camera-roll#3]
Hi guys,

rn-camera-roll package was working perfectly with react-native 0.15 but with 0.16 update, I get:

undefined is not a function (evaluating 'CameRoll.getPhotos')

Could you confirm me that this is something linked with the new react-native release ? 
Thanks in advance.
Guillaume

**Comment by Almouro** [comment]
Hi Guillaume,

We upgraded to 0.16 last week without any issue.

Can you show us some snippets of how you're using it? Maybe we'll be able to help.

**Comment by guillaumemorin** [comment]
Well, it seems that the problem is coming from Babel 6 exports http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default

The export default containing getPhotos method in index.android.js now produce {default: {getPhotos: ...}} if you import rn-camera-roll with require.

var test = require('rn-camera-roll');
console.log(test) // {default: {getPhotos: ...}}

Of course
var CameraRoll = require('rn-camera-roll').default will work 
import CameraRoll from 'rn-camera-roll'; and es6 import too...

**Comment by Almouro** [comment]
Ah yes, I forgot about that.
I'll update the example for Babel 6 and close the issue.
Thanks a lot! :)
